name: Prepare Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare releases')" # Skip merges from releases
    runs-on: tenki-standard-medium-4c-8g
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Setup Knope
        uses: knope-dev/action@19617851f9f13ab2f27a05989c55efb18aca3675 # v2.1.2
      - name: Prepare Release
        id: prepare
        run: knope prepare-release --verbose
        continue-on-error: true
      - name: Create Pull Request
        if: steps.prepare.outcome == 'success'
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          delete-branch: true
          commit-message: "chore: prepare releases"
          title: Release Versions
          base: main
          branch: release
          body: |
            This PR was automatically created to prepare the release versions. Close the PR when you are ready to release. See the changelog for more details.
